# Generated by Django 5.2.5 on 2025-08-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.farmerprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='users.farmerprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='users.farmerprofile'),
        ),
        migrations.AddField(
            model_name='report',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='report',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.farmerprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='users.farmerprofile'),
        ),
    ]
