# Generated by Django 5.2.5 on 2025-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, help_text='Optional name for the farm block', max_length=255, null=True)),
                ('location_detail', models.CharField(help_text='e.g., State, LGA, Village', max_length=255)),
                ('area_hectares', models.FloatField()),
                ('intended_crop_type', models.CharField(choices=[('Maize', 'Maize'), ('Rice', 'Rice'), ('Cassava', 'Cassava'), ('Yam', 'Yam'), ('Sorghum', 'Sorghum'), ('Millet', 'Millet'), ('Vegetables', 'Vegetables (e.g., Tomatoes, Pepper)'), ('Cocoa', 'Cocoa'), ('Other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_mapped', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
