# Generated by Django 5.2.5 on 2025-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='geometry_data',
            field=models.TextField(blank=True, help_text='GeoJSON string representing farm boundary', null=True),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='location_detail',
            field=models.CharField(help_text='e.g., State, LGA, Village (Can be auto-filled from map)', max_length=255),
        ),
    ]
