# Generated by Django 5.2.5 on 2025-08-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmland_geometry_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmland',
            old_name='date_mapped',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='farmland',
            name='geometry_data',
        ),
        migrations.AddField(
            model_name='farmland',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text='GeoJSON representation of the farm boundary', null=True),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='area_hectares',
            field=models.FloatField(help_text='Approximate area in hectares'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='farm_name',
            field=models.CharField(blank=True, help_text="Optional name for the farm e.g., 'Main Maize Field'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='intended_crop_type',
            field=models.CharField(help_text='e.g., Maize, Rice, Cassava', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='location_detail',
            field=models.CharField(help_text='State, LGA, Village (e.g., Kano, Dawakin Tofa, Gidan Kaya)', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about the farmland', null=True),
        ),
    ]
