# Generated by Django 5.2.5 on 2025-08-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('fertilizer', 'Fertilizer Application'), ('irrigation', 'Irrigation Advice'), ('pest_disease', 'Pest & Disease Warning'), ('yield_forecast', 'Yield Forecast Update'), ('soil_health', 'Soil Health Advice'), ('other', 'Other')], max_length=50)),
                ('recommendation_text', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('issued', 'Issued to Farmer'), ('completed', 'Completed by Farmer'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('agent_notes', models.TextField(blank=True, help_text="Agent's notes on issuing/following up.", null=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.farmland')),
            ],
        ),
    ]
